#!/usr/bin/env python3
"""Generate trainer-classes-i18n.json with translations for all 292 French trainer classes."""
import json, os

OUT = os.path.join(os.path.dirname(__file__), "src", "data", "trainer-classes-i18n.json")

# Full mapping: French class → {lang: translation}
MAPPING = {
  "Actrice": {"en":"Actress","de":"Schauspielerin","es":"Actriz","it":"Attrice","ja":"女優","ko":"여배우","pt-BR":"Atriz","zh-Hans":"女演员","zh-Hant":"女演員"},
  "Admin": {"en":"Admin","de":"Admin","es":"Admin","it":"Admin","ja":"かんぶ","ko":"간부","pt-BR":"Admin","zh-Hans":"干部","zh-Hant":"幹部"},
  "Admin Aqua": {"en":"Aqua Admin","de":"Aqua-Admin","es":"Admin Aqua","it":"Admin Acqua","ja":"アクアかんぶ","ko":"아쿠아단 간부","pt-BR":"Admin Aqua","zh-Hans":"海洋团干部","zh-Hant":"海洋團幹部"},
  "Admin Magma": {"en":"Magma Admin","de":"Magma-Admin","es":"Admin Magma","it":"Admin Magma","ja":"マグマかんぶ","ko":"마그마단 간부","pt-BR":"Admin Magma","zh-Hans":"熔岩团干部","zh-Hant":"熔岩團幹部"},
  "Admin Team": {"en":"Team Admin","de":"Team-Admin","es":"Admin del Equipo","it":"Admin del Team","ja":"チームかんぶ","ko":"팀 간부","pt-BR":"Admin do Team","zh-Hans":"队伍干部","zh-Hant":"隊伍幹部"},
  "Admin Team Aqua": {"en":"Team Aqua Admin","de":"Team Aqua-Admin","es":"Admin Team Aqua","it":"Admin Team Acqua","ja":"アクアだんかんぶ","ko":"아쿠아단 간부","pt-BR":"Admin Team Aqua","zh-Hans":"海洋队干部","zh-Hant":"海洋隊幹部"},
  "Admin Team Magma": {"en":"Team Magma Admin","de":"Team Magma-Admin","es":"Admin Team Magma","it":"Admin Team Magma","ja":"マグマだんかんぶ","ko":"마그마단 간부","pt-BR":"Admin Team Magma","zh-Hans":"熔岩队干部","zh-Hant":"熔岩隊幹部"},
  "Admin Team Skull": {"en":"Team Skull Admin","de":"Team Skull-Admin","es":"Admin Team Skull","it":"Admin Team Skull","ja":"スカルだんかんぶ","ko":"스컬단 간부","pt-BR":"Admin Team Skull","zh-Hans":"骷髅队干部","zh-Hant":"骷髏隊幹部"},
  "Agent": {"en":"Agent","de":"Agent","es":"Agente","it":"Agente","ja":"エージェント","ko":"요원","pt-BR":"Agente","zh-Hans":"特工","zh-Hant":"特工"},
  "Aroma": {"en":"Aroma Lady","de":"Aromadame","es":"Aromaterapista","it":"Aromatista","ja":"アロマなおねえさん","ko":"아로마아가씨","pt-BR":"Aromaterapista","zh-Hans":"芳香女士","zh-Hant":"芳香女士"},
  "Aromathérapeute": {"en":"Aroma Lady","de":"Aromadame","es":"Aromaterapista","it":"Aromatista","ja":"アロマなおねえさん","ko":"아로마아가씨","pt-BR":"Aromaterapista","zh-Hans":"芳香女士","zh-Hant":"芳香女士"},
  "Artiste": {"en":"Artist","de":"Künstler","es":"Artista","it":"Artista","ja":"アーティスト","ko":"아티스트","pt-BR":"Artista","zh-Hans":"艺术家","zh-Hant":"藝術家"},
  "Artistes de Rue": {"en":"Street Performers","de":"Straßenkünstler","es":"Artistas Callejeros","it":"Artisti di Strada","ja":"ストリートパフォーマー","ko":"거리 예술가","pt-BR":"Artistas de Rua","zh-Hans":"街头艺术家","zh-Hant":"街頭藝術家"},
  "Arôma": {"en":"Aroma Lady","de":"Aromadame","es":"Aromaterapista","it":"Aromatista","ja":"アロマなおねえさん","ko":"아로마아가씨","pt-BR":"Aromaterapista","zh-Hans":"芳香女士","zh-Hant":"芳香女士"},
  "Assistant": {"en":"Assistant","de":"Assistent","es":"Asistente","it":"Assistente","ja":"アシスタント","ko":"어시스턴트","pt-BR":"Assistente","zh-Hans":"助手","zh-Hant":"助手"},
  "Assistant Épreuve": {"en":"Trial Guide","de":"Prüfungsassistent","es":"Asistente de Prueba","it":"Assistente Prova","ja":"しれんのたすけ","ko":"시련 보조","pt-BR":"Assistente de Prova","zh-Hans":"试炼助手","zh-Hant":"試煉助手"},
  "Assistante de l'Épreuve": {"en":"Trial Guide","de":"Prüfungsassistentin","es":"Asistenta de Prueba","it":"Assistente della Prova","ja":"しれんのたすけ","ko":"시련 보조","pt-BR":"Assistente da Prova","zh-Hans":"试炼助手","zh-Hant":"試煉助手"},
  "Barista": {"en":"Barista","de":"Barista","es":"Barista","it":"Barista","ja":"バリスタ","ko":"바리스타","pt-BR":"Barista","zh-Hans":"咖啡师","zh-Hant":"咖啡師"},
  "Basketteur": {"en":"Basketball Player","de":"Basketballspieler","es":"Jugador de Baloncesto","it":"Cestista","ja":"バスケットボール選手","ko":"농구 선수","pt-BR":"Jogador de Basquete","zh-Hans":"篮球运动员","zh-Hant":"籃球運動員"},
  "Boss Team": {"en":"Team Boss","de":"Team-Boss","es":"Jefe del Team","it":"Boss del Team","ja":"チームのボス","ko":"팀 보스","pt-BR":"Chefe do Team","zh-Hans":"队伍首领","zh-Hant":"隊伍首領"},
  "Boss Team Flare": {"en":"Team Flare Boss","de":"Team Flare-Boss","es":"Jefe del Team Flare","it":"Boss del Team Flare","ja":"フレアだんボス","ko":"플레어단 보스","pt-BR":"Chefe do Team Flare","zh-Hans":"闪焰队首领","zh-Hant":"閃焰隊首領"},
  "Boss Team Skull": {"en":"Team Skull Boss","de":"Team Skull-Boss","es":"Jefe del Team Skull","it":"Boss del Team Skull","ja":"スカルだんボス","ko":"스컬단 보스","pt-BR":"Chefe do Team Skull","zh-Hans":"骷髅队首领","zh-Hant":"骷髏隊首領"},
  "Bouffon": {"en":"Jester","de":"Narr","es":"Bufón","it":"Buffone","ja":"ピエロ","ko":"광대","pt-BR":"Bobo","zh-Hans":"小丑","zh-Hant":"小丑"},
  "Boulangère": {"en":"Baker","de":"Bäckerin","es":"Panadera","it":"Panettiera","ja":"パン屋さん","ko":"제빵사","pt-BR":"Padeira","zh-Hans":"面包师","zh-Hant":"麵包師"},
  "Camarades de Karaté": {"en":"Karate Buddies","de":"Karatefreunde","es":"Amigos del Karate","it":"Compagni di Karate","ja":"カラテフレンズ","ko":"가라테 친구들","pt-BR":"Amigos de Karatê","zh-Hans":"空手道伙伴","zh-Hant":"空手道夥伴"},
  "Campeur": {"en":"Camper","de":"Wanderer","es":"Campista","it":"Campeggiatore","ja":"キャンパー","ko":"캠퍼","pt-BR":"Campista","zh-Hans":"露营者","zh-Hant":"露營者"},
  "Caméraman": {"en":"Cameraman","de":"Kameramann","es":"Camarógrafo","it":"Cameraman","ja":"カメラマン","ko":"카메라맨","pt-BR":"Cinegrafista","zh-Hans":"摄影师","zh-Hant":"攝影師"},
  "Canon": {"en":"Cannon","de":"Kanone","es":"Cañón","it":"Cannone","ja":"キャノン","ko":"캐논","pt-BR":"Canhão","zh-Hans":"大炮","zh-Hant":"大炮"},
  "Capitaine": {"en":"Captain","de":"Kapitän","es":"Capitán","it":"Capitano","ja":"キャプテン","ko":"캡틴","pt-BR":"Capitão","zh-Hans":"队长","zh-Hant":"隊長"},
  "Caïd": {"en":"Boss","de":"Anführer","es":"Capo","it":"Capo","ja":"ボス","ko":"두목","pt-BR":"Chefão","zh-Hans":"头目","zh-Hant":"頭目"},
  "Cerveau et Muscles": {"en":"Brains & Brawn","de":"Kopf und Muskeln","es":"Cerebro y Músculos","it":"Mente e Muscoli","ja":"ずのうとからだ","ko":"두뇌와 근육","pt-BR":"Cérebro e Músculos","zh-Hans":"智力与肌肉","zh-Hant":"智力與肌肉"},
  "Champion": {"en":"Champion","de":"Meister","es":"Campeón","it":"Campione","ja":"チャンピオン","ko":"챔피언","pt-BR":"Campeão","zh-Hans":"冠军","zh-Hant":"冠軍"},
  "Champion d'Arène": {"en":"Gym Leader","de":"Arenaleiter","es":"Líder de Gimnasio","it":"Capopalestra","ja":"ジムリーダー","ko":"체육관 관장","pt-BR":"Líder de Ginásio","zh-Hans":"道馆馆主","zh-Hant":"道館館主"},
  "Championne": {"en":"Champion","de":"Meisterin","es":"Campeona","it":"Campionessa","ja":"チャンピオン","ko":"챔피언","pt-BR":"Campeã","zh-Hans":"冠军","zh-Hant":"冠軍"},
  "Championne d'Arène": {"en":"Gym Leader","de":"Arenaleiterin","es":"Líder de Gimnasio","it":"Capopalestra","ja":"ジムリーダー","ko":"체육관 관장","pt-BR":"Líder de Ginásio","zh-Hans":"道馆馆主","zh-Hant":"道館館主"},
  "Champions": {"en":"Champions","de":"Meister","es":"Campeones","it":"Campioni","ja":"チャンピオンたち","ko":"챔피언들","pt-BR":"Campeões","zh-Hans":"冠军们","zh-Hant":"冠軍們"},
  "Chauffeur de Taxi": {"en":"Taxi Driver","de":"Taxifahrer","es":"Taxista","it":"Tassista","ja":"タクシードライバー","ko":"택시 기사","pt-BR":"Motorista de Táxi","zh-Hans":"出租车司机","zh-Hant":"計程車司機"},
  "Chef Galaxie": {"en":"Galactic Commander","de":"Galaxie-Chef","es":"Comandante Galaxia","it":"Comandante Galassia","ja":"ギンガのボス","ko":"갤럭시단 간부","pt-BR":"Comandante Galáxia","zh-Hans":"银河队首领","zh-Hant":"銀河隊首領"},
  "Cheminot": {"en":"Railway Worker","de":"Eisenbahner","es":"Ferroviario","it":"Ferroviere","ja":"てつどういん","ko":"철도원","pt-BR":"Ferroviário","zh-Hans":"铁路工人","zh-Hant":"鐵路工人"},
  "Clown": {"en":"Clown","de":"Clown","es":"Payaso","it":"Pagliaccio","ja":"ピエロ","ko":"광대","pt-BR":"Palhaço","zh-Hans":"小丑","zh-Hant":"小丑"},
  "Colay-Monthé": {"en":"Collector","de":"Sammler","es":"Coleccionista","it":"Collezionista","ja":"コレクレー","ko":"콜레크레","pt-BR":"Colecionador","zh-Hans":"收藏家","zh-Hant":"收藏家"},
  "Collec": {"en":"Collector","de":"Sammler","es":"Coleccionista","it":"Collezionista","ja":"コレクター","ko":"수집가","pt-BR":"Colecionador","zh-Hans":"收藏家","zh-Hant":"收藏家"},
  "Collectionneur": {"en":"Collector","de":"Sammler","es":"Coleccionista","it":"Collezionista","ja":"コレクター","ko":"수집가","pt-BR":"Colecionador","zh-Hans":"收藏家","zh-Hant":"收藏家"},
  "Collègues de bureau": {"en":"Office Workers","de":"Büroangestellte","es":"Compañeros de Oficina","it":"Colleghi d'Ufficio","ja":"オフィスの同僚","ko":"직장 동료","pt-BR":"Colegas de Escritório","zh-Hans":"办公室同事","zh-Hant":"辦公室同事"},
  "Combattante": {"en":"Fighter","de":"Kämpferin","es":"Luchadora","it":"Combattente","ja":"ファイター","ko":"파이터","pt-BR":"Lutadora","zh-Hans":"女战士","zh-Hant":"女戰士"},
  "Commandant": {"en":"Commander","de":"Kommandant","es":"Comandante","it":"Comandante","ja":"コマンダー","ko":"사령관","pt-BR":"Comandante","zh-Hans":"指挥官","zh-Hant":"指揮官"},
  "Complices": {"en":"Accomplices","de":"Komplizen","es":"Cómplices","it":"Complici","ja":"なかまたち","ko":"공범들","pt-BR":"Cúmplices","zh-Hans":"同伙","zh-Hant":"同夥"},
  "Conseil": {"en":"Council","de":"Rat","es":"Consejo","it":"Consiglio","ja":"かいぎ","ko":"의회","pt-BR":"Conselho","zh-Hans":"理事会","zh-Hant":"理事會"},
  "Conseil 4": {"en":"Elite Four","de":"Top-Vier","es":"Alto Mando","it":"Superquattro","ja":"したいよんてん","ko":"사천왕","pt-BR":"Elite dos Quatro","zh-Hans":"四天王","zh-Hant":"四天王"},
  "Contrôleur": {"en":"Inspector","de":"Kontrolleur","es":"Inspector","it":"Controllore","ja":"コントローラー","ko":"검표원","pt-BR":"Inspetor","zh-Hans":"检查员","zh-Hant":"檢查員"},
  "Couple Cool": {"en":"Cool Couple","de":"Cooles Paar","es":"Pareja Guay","it":"Coppia Cool","ja":"クールなカップル","ko":"멋진 커플","pt-BR":"Casal Descolado","zh-Hans":"酷炫情侣","zh-Hant":"酷炫情侶"},
  "Couple de Nageurs": {"en":"Swimming Couple","de":"Schwimmpaar","es":"Pareja de Nadadores","it":"Coppia di Nuotatori","ja":"スイマーカップル","ko":"수영 커플","pt-BR":"Casal de Nadadores","zh-Hans":"游泳情侣","zh-Hant":"游泳情侶"},
  "Couple de Pokéfans": {"en":"Pokéfan Couple","de":"Pokéfan-Paar","es":"Pareja Pokéfan","it":"Coppia Pokéfan","ja":"ポケファンカップル","ko":"포케팬 커플","pt-BR":"Casal Pokéfan","zh-Hans":"宝可梦迷情侣","zh-Hant":"寶可夢迷情侶"},
  "Cowgirl": {"en":"Cowgirl","de":"Cowgirl","es":"Vaquera","it":"Cowgirl","ja":"カウガール","ko":"카우걸","pt-BR":"Cowgirl","zh-Hans":"牛仔女","zh-Hant":"牛仔女"},
  "Crache-Feu": {"en":"Fire Breather","de":"Feuerspucker","es":"Escupefuego","it":"Sputafuoco","ja":"ファイアイーター","ko":"불 뿜는 사람","pt-BR":"Cuspidor de Fogo","zh-Hans":"喷火手","zh-Hant":"噴火手"},
  "Crache-feu": {"en":"Fire Breather","de":"Feuerspucker","es":"Escupefuego","it":"Sputafuoco","ja":"ファイアイーター","ko":"불 뿜는 사람","pt-BR":"Cuspidor de Fogo","zh-Hans":"喷火手","zh-Hant":"噴火手"},
  "Croupier": {"en":"Croupier","de":"Croupier","es":"Crupier","it":"Croupier","ja":"ディーラー","ko":"딜러","pt-BR":"Crupiê","zh-Hans":"荷官","zh-Hant":"荷官"},
  "Cuisinier": {"en":"Cook","de":"Koch","es":"Cocinero","it":"Cuoco","ja":"コック","ko":"요리사","pt-BR":"Cozinheiro","zh-Hans":"厨师","zh-Hant":"廚師"},
  "Cuisinière": {"en":"Cook","de":"Köchin","es":"Cocinera","it":"Cuoca","ja":"コック","ko":"요리사","pt-BR":"Cozinheira","zh-Hans":"女厨师","zh-Hant":"女廚師"},
  "Cycliste": {"en":"Cyclist","de":"Radfahrer","es":"Ciclista","it":"Ciclista","ja":"サイクリスト","ko":"사이클리스트","pt-BR":"Ciclista","zh-Hans":"骑行者","zh-Hant":"騎行者"},
  "Danseur": {"en":"Dancer","de":"Tänzer","es":"Bailarín","it":"Ballerino","ja":"ダンサー","ko":"댄서","pt-BR":"Dançarino","zh-Hans":"舞蹈演员","zh-Hant":"舞蹈演員"},
  "Danseuse": {"en":"Dancer","de":"Tänzerin","es":"Bailarina","it":"Ballerina","ja":"ダンサー","ko":"댄서","pt-BR":"Dançarina","zh-Hans":"女舞蹈演员","zh-Hant":"女舞蹈演員"},
  "Danseuses en Famille": {"en":"Family Dancers","de":"Familientänzerinnen","es":"Bailarinas en Familia","it":"Ballerine in Famiglia","ja":"かぞくダンサー","ko":"가족 댄서","pt-BR":"Dançarinas em Família","zh-Hans":"家庭舞蹈家","zh-Hant":"家庭舞蹈家"},
  "Directeur": {"en":"Director","de":"Direktor","es":"Director","it":"Direttore","ja":"ディレクター","ko":"감독","pt-BR":"Diretor","zh-Hans":"主任","zh-Hant":"主任"},
  "Directrice": {"en":"Director","de":"Direktorin","es":"Directora","it":"Direttrice","ja":"ディレクター","ko":"감독","pt-BR":"Diretora","zh-Hans":"主任","zh-Hant":"主任"},
  "Docteur": {"en":"Doctor","de":"Arzt","es":"Doctor","it":"Dottore","ja":"ドクター","ko":"의사","pt-BR":"Doutor","zh-Hans":"医生","zh-Hant":"醫生"},
  "Docteure": {"en":"Doctor","de":"Ärztin","es":"Doctora","it":"Dottoressa","ja":"ドクター","ko":"의사","pt-BR":"Doutora","zh-Hans":"女医生","zh-Hant":"女醫生"},
  "Dompteur": {"en":"Tamer","de":"Dompteur","es":"Domador","it":"Domatore","ja":"ビーストテイマー","ko":"조련사","pt-BR":"Domador","zh-Hans":"驯兽师","zh-Hant":"馴獸師"},
  "Doyen": {"en":"Elder","de":"Ältester","es":"Anciano","it":"Anziano","ja":"ちょうろう","ko":"장로","pt-BR":"Ancião","zh-Hans":"长老","zh-Hant":"長老"},
  "Doyenne": {"en":"Elder","de":"Älteste","es":"Anciana","it":"Anziana","ja":"ちょうろう","ko":"장로","pt-BR":"Anciã","zh-Hans":"女长老","zh-Hant":"女長老"},
  "Dracologue": {"en":"Dragon Tamer","de":"Drachenbezwinger","es":"Domador de Dragones","it":"Domatore di Draghi","ja":"ドラゴンテイマー","ko":"드래곤 조련사","pt-BR":"Domador de Dragões","zh-Hans":"驯龙师","zh-Hant":"馴龍師"},
  "Dresseur": {"en":"Pokémon Trainer","de":"Trainer","es":"Entrenador","it":"Allenatore","ja":"ポケモントレーナー","ko":"포켓몬 트레이너","pt-BR":"Treinador","zh-Hans":"训练师","zh-Hant":"訓練師"},
  "Dresseur Aérien": {"en":"Ace Trainer","de":"Ace-Trainer","es":"Entrenador Maestro","it":"Asso Allenatore","ja":"エースをねらえ","ko":"에이스 트레이너","pt-BR":"Ás Treinador","zh-Hans":"王牌训练师","zh-Hant":"王牌訓練師"},
  "Dresseur Prometteur": {"en":"Pokémon Breeder","de":"Pokémon-Züchter","es":"Criador de Pokémon","it":"Allevatore Pokémon","ja":"そだてやさん","ko":"포켓몬 브리더","pt-BR":"Criador Pokémon","zh-Hans":"宝可梦培育师","zh-Hant":"寶可夢培育師"},
  "Dresseur d'Arène": {"en":"Gym Trainer","de":"Arenatrainer","es":"Entrenador de Gimnasio","it":"Allenatore del Palestra","ja":"ジムトレーナー","ko":"체육관 트레이너","pt-BR":"Treinador de Ginásio","zh-Hans":"道馆训练师","zh-Hant":"道館訓練師"},
  "Dresseur en Herbe": {"en":"Young Trainer","de":"Junger Trainer","es":"Entrenador Novato","it":"Giovane Allenatore","ja":"わかてトレーナー","ko":"풋내기 트레이너","pt-BR":"Treinador Jovem","zh-Hans":"新手训练师","zh-Hant":"新手訓練師"},
  "Dresseurs Jean-Targe": {"en":"Bug Catcher","de":"Käferfänger","es":"Cazainsectos","it":"Cacciatore d'Insetti","ja":"むしとりしょうねん","ko":"벌레잡이 소년","pt-BR":"Caçador de Insetos","zh-Hans":"捉虫少年","zh-Hant":"捉蟲少年"},
  "Dresseurs d'Élite": {"en":"Elite Trainers","de":"Elite-Trainer","es":"Entrenadores de Élite","it":"Allenatori d'Élite","ja":"エリートトレーナー","ko":"엘리트 트레이너","pt-BR":"Treinadores de Elite","zh-Hans":"精英训练师","zh-Hant":"精英訓練師"},
  "Dresseurs en Herbe": {"en":"Young Trainers","de":"Junge Trainer","es":"Entrenadores Novatos","it":"Giovani Allenatori","ja":"わかてトレーナーたち","ko":"풋내기 트레이너들","pt-BR":"Treinadores Jovens","zh-Hans":"新手训练师们","zh-Hant":"新手訓練師們"},
  "Dresseuse": {"en":"Pokémon Trainer","de":"Trainerin","es":"Entrenadora","it":"Allenatrice","ja":"ポケモントレーナー","ko":"포켓몬 트레이너","pt-BR":"Treinadora","zh-Hans":"女训练师","zh-Hant":"女訓練師"},
  "Dresseuse Kimono": {"en":"Kimono Girl","de":"Kimono-Dame","es":"Chica Kimono","it":"Ragazza in Kimono","ja":"キモノのおんなのこ","ko":"기모노 소녀","pt-BR":"Garota Kimono","zh-Hans":"和服少女","zh-Hant":"和服少女"},
  "Dresseuse d'Arène": {"en":"Gym Trainer","de":"Arenatrainerin","es":"Entrenadora de Gimnasio","it":"Allenatrice del Palestra","ja":"ジムトレーナー","ko":"체육관 트레이너","pt-BR":"Treinadora de Ginásio","zh-Hans":"道馆训练师","zh-Hant":"道館訓練師"},
  "Dresseuse en Herbe": {"en":"Young Trainer","de":"Junge Trainerin","es":"Entrenadora Novata","it":"Giovane Allenatrice","ja":"わかてトレーナー","ko":"풋내기 트레이너","pt-BR":"Treinadora Jovem","zh-Hans":"新手训练师","zh-Hant":"新手訓練師"},
  "Duo": {"en":"Duo","de":"Duo","es":"Dúo","it":"Duo","ja":"デュオ","ko":"듀오","pt-BR":"Dupla","zh-Hans":"二人组","zh-Hant":"二人組"},
  "Duo Baston": {"en":"Battle Duo","de":"Kampfduo","es":"Dúo de Batalla","it":"Duo Battaglia","ja":"バトルデュオ","ko":"배틀 듀오","pt-BR":"Dupla de Batalha","zh-Hans":"对战二人组","zh-Hant":"對戰二人組"},
  "Duo de Rangers": {"en":"Ranger Duo","de":"Ranger-Duo","es":"Dúo de Rangers","it":"Duo di Ranger","ja":"レンジャーデュオ","ko":"레인저 듀오","pt-BR":"Dupla de Rangers","zh-Hans":"巡护员二人组","zh-Hant":"巡護員二人組"},
  "Employé": {"en":"Employee","de":"Angestellter","es":"Empleado","it":"Dipendente","ja":"じゅうぎょういん","ko":"직원","pt-BR":"Funcionário","zh-Hans":"职员","zh-Hant":"職員"},
  "Employé de la Ligue": {"en":"League Staff","de":"Liga-Mitarbeiter","es":"Empleado de la Liga","it":"Dipendente della Lega","ja":"リーグのしゃいん","ko":"리그 직원","pt-BR":"Funcionário da Liga","zh-Hans":"联盟职员","zh-Hant":"聯盟職員"},
  "Employé Æther & Directeur": {"en":"Aether Employee & Director","de":"Äther-Mitarbeiter & Direktor","es":"Empleado Æther & Director","it":"Dipendente Æther & Direttore","ja":"エーテルのしゃいん","ko":"에테르 직원","pt-BR":"Funcionário Æther & Diretor","zh-Hans":"以太财团职员","zh-Hant":"以太財團職員"},
  "Employée": {"en":"Employee","de":"Angestellte","es":"Empleada","it":"Dipendente","ja":"じゅうぎょういん","ko":"직원","pt-BR":"Funcionária","zh-Hans":"女职员","zh-Hant":"女職員"},
  "Entomomaniac": {"en":"Bug Maniac","de":"Käferfreak","es":"Maníaco de los Bichos","it":"Maniaco degli Insetti","ja":"むしとりマニア","ko":"벌레 마니아","pt-BR":"Maníaco por Insetos","zh-Hans":"虫虫迷","zh-Hant":"蟲蟲迷"},
  "Exorciste": {"en":"Channeler","de":"Seher","es":"Invocadora","it":"Sensitiva","ja":"いたこ","ko":"무당","pt-BR":"Vidente","zh-Hans":"灵媒","zh-Hant":"靈媒"},
  "Expert": {"en":"Expert","de":"Experte","es":"Experto","it":"Esperto","ja":"エキスパート","ko":"전문가","pt-BR":"Especialista","zh-Hans":"专家","zh-Hant":"專家"},
  "Experte": {"en":"Expert","de":"Expertin","es":"Experta","it":"Esperta","ja":"エキスパート","ko":"전문가","pt-BR":"Especialista","zh-Hans":"女专家","zh-Hant":"女專家"},
  "Facteur": {"en":"Delivery Man","de":"Briefträger","es":"Cartero","it":"Postino","ja":"はいたつびと","ko":"배달부","pt-BR":"Carteiro","zh-Hans":"邮递员","zh-Hant":"郵遞員"},
  "Famille Stratège": {"en":"Strategist Family","de":"Strategen-Familie","es":"Familia Estratega","it":"Famiglia Strategia","ja":"せんりゃくかぞく","ko":"전략 가족","pt-BR":"Família Estrategista","zh-Hans":"战略家庭","zh-Hant":"戰略家庭"},
  "Famille d'Artistes": {"en":"Artist Family","de":"Künstlerfamilie","es":"Familia de Artistas","it":"Famiglia d'Artisti","ja":"アーティストかぞく","ko":"예술인 가족","pt-BR":"Família de Artistas","zh-Hans":"艺术家家庭","zh-Hant":"藝術家家庭"},
  "Fan de Camping": {"en":"Camping Fan","de":"Camping-Fan","es":"Aficionado al Camping","it":"Fan del Campeggio","ja":"キャンプファン","ko":"캠핑 팬","pt-BR":"Fã de Camping","zh-Hans":"露营爱好者","zh-Hant":"露營愛好者"},
  "Fan de Moto": {"en":"Biker","de":"Motorradfan","es":"Fanático de las Motos","it":"Fan delle Moto","ja":"バイクファン","ko":"오토바이 팬","pt-BR":"Fã de Moto","zh-Hans":"摩托车迷","zh-Hant":"摩托車迷"},
  "Fan de Pique-Nique": {"en":"Picnic Fan","de":"Picknick-Fan","es":"Aficionado al Picnic","it":"Fan del Picnic","ja":"ピクニックファン","ko":"피크닉 팬","pt-BR":"Fã de Piquenique","zh-Hans":"野餐爱好者","zh-Hant":"野餐愛好者"},
  "Fans de Capoeira": {"en":"Capoeira Fans","de":"Capoeira-Fans","es":"Fanáticos de la Capoeira","it":"Fan della Capoeira","ja":"カポエイラファン","ko":"카포에이라 팬","pt-BR":"Fãs de Capoeira","zh-Hans":"卡波耶拉迷","zh-Hant":"卡波耶拉迷"},
  "Fermier": {"en":"Farmer","de":"Bauer","es":"Granjero","it":"Contadino","ja":"のうえん","ko":"농부","pt-BR":"Fazendeiro","zh-Hans":"农民","zh-Hant":"農民"},
  "Fermiers en famille": {"en":"Farmer Family","de":"Bauernfamilie","es":"Familia de Granjeros","it":"Famiglia di Contadini","ja":"のうえんかぞく","ko":"농부 가족","pt-BR":"Família de Agricultores","zh-Hans":"农民家庭","zh-Hant":"農民家庭"},
  "Fille & Père": {"en":"Girl & Father","de":"Mädchen & Vater","es":"Chica y Padre","it":"Figlia e Padre","ja":"おとことおんなのこ","ko":"소녀와 아버지","pt-BR":"Garota e Pai","zh-Hans":"父女","zh-Hant":"父女"},
  "Fille Baston": {"en":"Battle Girl","de":"Kampfmädchen","es":"Chica Batalla","it":"Ragazza Battaglia","ja":"バトルガール","ko":"배틀 걸","pt-BR":"Garota de Batalha","zh-Hans":"对战女孩","zh-Hant":"對戰女孩"},
  "Fille en Kimono": {"en":"Kimono Girl","de":"Kimono-Mädchen","es":"Chica Kimono","it":"Ragazza in Kimono","ja":"キモノのおんなのこ","ko":"기모노 소녀","pt-BR":"Garota Kimono","zh-Hans":"和服女孩","zh-Hant":"和服女孩"},
  "Fille à la Bouée": {"en":"Tuber","de":"Schlauchbootfahrerin","es":"Flotadora","it":"Ciambellaia","ja":"チューブのおんなのこ","ko":"튜브 소녀","pt-BR":"Garota com Boia","zh-Hans":"游泳圈女孩","zh-Hant":"游泳圈女孩"},
  "Fillette": {"en":"Little Girl","de":"Kleines Mädchen","es":"Niña","it":"Bambina","ja":"ちいさなおんなのこ","ko":"꼬마 소녀","pt-BR":"Menininha","zh-Hans":"小女孩","zh-Hant":"小女孩"},
  "Fillette de Conte": {"en":"Fairytale Girl","de":"Märchenmädchen","es":"Chica de Cuento","it":"Bambina da Favola","ja":"おとぎばなしのおんなのこ","ko":"동화 속 소녀","pt-BR":"Garota de Conto de Fadas","zh-Hans":"童话少女","zh-Hant":"童話少女"},
  "Flotteur": {"en":"Tuber","de":"Schlauchbootfahrer","es":"Flotador","it":"Ciambellaro","ja":"チューブのおとこのこ","ko":"튜브 소년","pt-BR":"Flutuador","zh-Hans":"游泳圈男孩","zh-Hant":"游泳圈男孩"},
  "Fondation Æther": {"en":"Aether Foundation","de":"Äther-Stiftung","es":"Fundación Æther","it":"Fondazione Æther","ja":"エーテル財団","ko":"에테르 재단","pt-BR":"Fundação Æther","zh-Hans":"以太财团","zh-Hant":"以太財團"},
  "Frère et Soeur": {"en":"Siblings","de":"Geschwister","es":"Hermano y Hermana","it":"Fratello e Sorella","ja":"きょうだい","ko":"남매","pt-BR":"Irmão e Irmã","zh-Hans":"兄妹","zh-Hant":"兄妹"},
  "GAME FREAK": {"en":"GAME FREAK","de":"GAME FREAK","es":"GAME FREAK","it":"GAME FREAK","ja":"ゲームフリーク","ko":"게임 프리크","pt-BR":"GAME FREAK","zh-Hans":"GAME FREAK","zh-Hant":"GAME FREAK"},
  "Gamin": {"en":"Kid","de":"Kind","es":"Chico","it":"Ragazzino","ja":"わんぱくしょうねん","ko":"꼬마","pt-BR":"Garoto","zh-Hans":"小男孩","zh-Hant":"小男孩"},
  "Gang des Allumés": {"en":"Punk Gang","de":"Zündler-Gang","es":"Pandilla Encendida","it":"Gang degli Accesi","ja":"やんちゃギャング","ko":"불꽃 갱단","pt-BR":"Gangue dos Inflamados","zh-Hans":"点火帮","zh-Hant":"點火幫"},
  "Garçon de Café": {"en":"Café Staff","de":"Kaffeehausangestellter","es":"Empleado de Café","it":"Cameriere del Caffè","ja":"カフェのスタッフ","ko":"카페 직원","pt-BR":"Funcionário de Café","zh-Hans":"咖啡厅员工","zh-Hant":"咖啡廳員工"},
  "Garçon à la Bouée": {"en":"Tuber","de":"Schlauchbootfahrer","es":"Flotador","it":"Ciambellaro","ja":"チューブのおとこのこ","ko":"튜브 소년","pt-BR":"Menino com Boia","zh-Hans":"游泳圈男孩","zh-Hant":"游泳圈男孩"},
  "Gentleman": {"en":"Gentleman","de":"Gentleman","es":"Caballero","it":"Gentiluomo","ja":"ジェントルマン","ko":"신사","pt-BR":"Cavalheiro","zh-Hans":"绅士","zh-Hant":"紳士"},
  "Golfeur": {"en":"Golfer","de":"Golfspieler","es":"Golfista","it":"Golfista","ja":"ゴルファー","ko":"골퍼","pt-BR":"Golfista","zh-Hans":"高尔夫球手","zh-Hant":"高爾夫球手"},
  "Golfeuse": {"en":"Golfer","de":"Golfspielerin","es":"Golfista","it":"Golfista","ja":"ゴルファー","ko":"골퍼","pt-BR":"Golfista","zh-Hans":"女高尔夫球手","zh-Hant":"女高爾夫球手"},
  "Golfeuses": {"en":"Golfers","de":"Golfspielerinnen","es":"Golfistas","it":"Golfiste","ja":"ゴルファーたち","ko":"골퍼들","pt-BR":"Golfistas","zh-Hans":"女高尔夫球手们","zh-Hant":"女高爾夫球手們"},
  "Gouvernante": {"en":"Housekeeper","de":"Haushälterin","es":"Ama de Llaves","it":"Governante","ja":"かじのおてつだい","ko":"가정부","pt-BR":"Governanta","zh-Hans":"女管家","zh-Hant":"女管家"},
  "Groom": {"en":"Groom","de":"Bräutigam","es":"Novio","it":"Sposo","ja":"しんろう","ko":"신랑","pt-BR":"Noivo","zh-Hans":"新郎","zh-Hant":"新郎"},
  "Guitariste": {"en":"Guitarist","de":"Gitarrist","es":"Guitarrista","it":"Chitarrista","ja":"ギタリスト","ko":"기타리스트","pt-BR":"Guitarrista","zh-Hans":"吉他手","zh-Hant":"吉他手"},
  "Héritière": {"en":"Lady","de":"Erbin","es":"Señorita","it":"Ereditiera","ja":"レディ","ko":"귀부인","pt-BR":"Herdeira","zh-Hans":"千金小姐","zh-Hant":"千金小姐"},
  "Infirmier": {"en":"Nurse","de":"Krankenpfleger","es":"Enfermero","it":"Infermiere","ja":"かんごし","ko":"간호사","pt-BR":"Enfermeiro","zh-Hans":"男护士","zh-Hant":"男護士"},
  "Infirmière": {"en":"Nurse","de":"Krankenschwester","es":"Enfermera","it":"Infermiera","ja":"かんごし","ko":"간호사","pt-BR":"Enfermeira","zh-Hans":"护士","zh-Hant":"護士"},
  "Influenceuse": {"en":"Influencer","de":"Influencerin","es":"Influencer","it":"Influencer","ja":"インフルエンサー","ko":"인플루언서","pt-BR":"Influenciadora","zh-Hans":"网红","zh-Hant":"網紅"},
  "Intello": {"en":"Nerd","de":"Streber","es":"Empollón","it":"Secchione","ja":"ガリ勉","ko":"공부벌레","pt-BR":"Nerd","zh-Hans":"书呆子","zh-Hant":"書呆子"},
  "Interviewer": {"en":"Interviewer","de":"Interviewer","es":"Entrevistador","it":"Intervistatore","ja":"インタビュアー","ko":"인터뷰어","pt-BR":"Entrevistador","zh-Hans":"采访者","zh-Hant":"採訪者"},
  "Intrépides": {"en":"Daring Duo","de":"Verwegene","es":"Intrépidos","it":"Intrepidi","ja":"だいたんなふたり","ko":"대담한 듀오","pt-BR":"Intrépidos","zh-Hans":"大胆组合","zh-Hant":"大膽組合"},
  "Jardinier": {"en":"Gardener","de":"Gärtner","es":"Jardinero","it":"Giardiniere","ja":"ガーデナー","ko":"정원사","pt-BR":"Jardineiro","zh-Hans":"园丁","zh-Hant":"園丁"},
  "Jeune Couple": {"en":"Young Couple","de":"Junges Paar","es":"Pareja Joven","it":"Coppia Giovane","ja":"わかいカップル","ko":"젊은 커플","pt-BR":"Casal Jovem","zh-Hans":"年轻情侣","zh-Hant":"年輕情侶"},
  "Jeune Sportive": {"en":"Young Athlete","de":"Junge Sportlerin","es":"Joven Deportista","it":"Giovane Sportiva","ja":"わかいスポーツちゃん","ko":"젊은 운동선수","pt-BR":"Jovem Atleta","zh-Hans":"年轻运动员","zh-Hant":"年輕運動員"},
  "Jeunes Tourtereaux": {"en":"Young Couple","de":"Junges Pärchen","es":"Tortolitos Jóvenes","it":"Giovani Innamorati","ja":"わかいラブラブ","ko":"젊은 사랑꾼들","pt-BR":"Jovens Apaixonados","zh-Hans":"年轻恋人","zh-Hant":"年輕戀人"},
  "Joggeur": {"en":"Jogger","de":"Jogger","es":"Trotador","it":"Jogger","ja":"ジョガー","ko":"조거","pt-BR":"Corredor","zh-Hans":"慢跑者","zh-Hant":"慢跑者"},
  "Jongleur": {"en":"Juggler","de":"Jongleur","es":"Malabarista","it":"Giocoliere","ja":"ジャグラー","ko":"저글러","pt-BR":"Malabarista","zh-Hans":"杂技师","zh-Hant":"雜技師"},
  "Joueur": {"en":"Player","de":"Spieler","es":"Jugador","it":"Giocatore","ja":"ゲームプレイヤー","ko":"플레이어","pt-BR":"Jogador","zh-Hans":"玩家","zh-Hant":"玩家"},
  "Journalistes": {"en":"Journalists","de":"Journalisten","es":"Periodistas","it":"Giornalisti","ja":"ジャーナリスト","ko":"기자들","pt-BR":"Jornalistas","zh-Hans":"记者们","zh-Hant":"記者們"},
  "Jumelles": {"en":"Twins","de":"Zwillinge","es":"Gemelas","it":"Gemelle","ja":"ふたご","ko":"쌍둥이","pt-BR":"Gêmeas","zh-Hans":"双胞胎女孩","zh-Hant":"雙胞胎女孩"},
  "Karateka": {"en":"Black Belt","de":"Schwarzgurt","es":"Cinturón Negro","it":"Cintura Nera","ja":"カラテおう","ko":"격투 고수","pt-BR":"Cinturão Negro","zh-Hans":"空手道高手","zh-Hant":"空手道高手"},
  "Karatéka": {"en":"Black Belt","de":"Schwarzgurt","es":"Cinturón Negro","it":"Cintura Nera","ja":"カラテおう","ko":"격투 고수","pt-BR":"Cinturão Negro","zh-Hans":"空手道高手","zh-Hant":"空手道高手"},
  "Karatéka et Petit": {"en":"Black Belt & Kid","de":"Schwarzgurt & Kind","es":"Cinturón Negro y Niño","it":"Cintura Nera e Bambino","ja":"カラテおうとこども","ko":"격투 고수와 꼬마","pt-BR":"Cinturão Negro e Criança","zh-Hans":"空手道高手和孩子","zh-Hant":"空手道高手和孩子"},
  "Karatékas Sr. et Jr.": {"en":"Black Belt Sr. & Jr.","de":"Schwarzgurt Sr. & Jr.","es":"Cinturón Negro Sr. y Jr.","it":"Cintura Nera Sr. e Jr.","ja":"カラテおうシニアジュニア","ko":"격투 고수 시니어 & 주니어","pt-BR":"Cinturão Negro Sr. e Jr.","zh-Hans":"空手道高手前辈后辈","zh-Hant":"空手道高手前輩後輩"},
  "Kinésiste": {"en":"Physiotherapist","de":"Physiotherapeut","es":"Fisioterapeuta","it":"Fisioterapista","ja":"フィジカルセラピスト","ko":"물리치료사","pt-BR":"Fisioterapeuta","zh-Hans":"理疗师","zh-Hant":"理療師"},
  "Leader Magma": {"en":"Magma Leader","de":"Magma-Anführer","es":"Jefe Magma","it":"Leader Magma","ja":"マグマだんリーダー","ko":"마그마단 리더","pt-BR":"Líder Magma","zh-Hans":"熔岩团首领","zh-Hant":"熔岩團首領"},
  "Leader Team Aqua": {"en":"Team Aqua Leader","de":"Team Aqua-Anführer","es":"Jefe Team Aqua","it":"Leader Team Acqua","ja":"アクアだんリーダー","ko":"아쿠아단 리더","pt-BR":"Líder Team Aqua","zh-Hans":"海洋团首领","zh-Hant":"海洋團首領"},
  "Leader Team Magma": {"en":"Team Magma Leader","de":"Team Magma-Anführer","es":"Jefe Team Magma","it":"Leader Team Magma","ja":"マグマだんリーダー","ko":"마그마단 리더","pt-BR":"Líder Team Magma","zh-Hans":"熔岩团首领","zh-Hant":"熔岩團首領"},
  "Livreur": {"en":"Delivery Man","de":"Lieferbote","es":"Repartidor","it":"Corriere","ja":"はいたつびと","ko":"배달원","pt-BR":"Entregador","zh-Hans":"快递员","zh-Hant":"快遞員"},
  "Loubard": {"en":"Punk","de":"Rowdy","es":"Gamberro","it":"Bullo","ja":"チンピラ","ko":"불량배","pt-BR":"Valentão","zh-Hans":"混混","zh-Hant":"混混"},
  "Loubards": {"en":"Punks","de":"Rowdys","es":"Gamberros","it":"Bulli","ja":"チンピラたち","ko":"불량배들","pt-BR":"Valentões","zh-Hans":"混混们","zh-Hant":"混混們"},
  "Macro Cosmos": {"en":"Macro Cosmos","de":"Macro Cosmos","es":"Macro Cosmos","it":"Macro Cosmos","ja":"マクロコスモス","ko":"매크로 코스모스","pt-BR":"Macro Cosmos","zh-Hans":"宏观宇宙","zh-Hant":"宏觀宇宙"},
  "Mademoiselle": {"en":"Lady","de":"Fräulein","es":"Señorita","it":"Signorina","ja":"お嬢さん","ko":"아가씨","pt-BR":"Senhorita","zh-Hans":"小姐","zh-Hant":"小姐"},
  "Majordome": {"en":"Butler","de":"Butler","es":"Mayordomo","it":"Maggiordomo","ja":"バトラー","ko":"집사","pt-BR":"Mordomo","zh-Hans":"管家","zh-Hant":"管家"},
  "Marin": {"en":"Sailor","de":"Matrose","es":"Marinero","it":"Marinaio","ja":"かいこうし","ko":"선원","pt-BR":"Marinheiro","zh-Hans":"水手","zh-Hant":"水手"},
  "Mauvaises Graines": {"en":"Bad Seeds","de":"Üble Brut","es":"Malas Hierbas","it":"Cattive Erbe","ja":"わるいたね","ko":"나쁜 씨앗들","pt-BR":"Sementes Ruins","zh-Hans":"坏种子","zh-Hant":"壞種子"},
  "Maître": {"en":"Master","de":"Meister","es":"Maestro","it":"Maestro","ja":"マスター","ko":"마스터","pt-BR":"Mestre","zh-Hans":"大师","zh-Hant":"大師"},
  "Maître de la Ligue": {"en":"League Master","de":"Liga-Meister","es":"Maestro de la Liga","it":"Maestro della Lega","ja":"リーグマスター","ko":"리그 마스터","pt-BR":"Mestre da Liga","zh-Hans":"联盟大师","zh-Hant":"聯盟大師"},
  "Maître du Dojo": {"en":"Dojo Master","de":"Dojo-Meister","es":"Maestro del Dojo","it":"Maestro del Dojo","ja":"どうじょうのおやかた","ko":"도장 관장","pt-BR":"Mestre do Dojo","zh-Hans":"道场馆主","zh-Hant":"道場館主"},
  "Maîtresse": {"en":"Mistress","de":"Meisterin","es":"Maestra","it":"Maestra","ja":"マスター","ko":"마스터","pt-BR":"Mestra","zh-Hans":"女大师","zh-Hant":"女大師"},
  "Maîtresse en Chef": {"en":"Head Mistress","de":"Oberlehrerin","es":"Directora","it":"Preside","ja":"チーフ","ko":"수석 마스터","pt-BR":"Chefe Suprema","zh-Hans":"总管","zh-Hant":"總管"},
  "Medium": {"en":"Medium","de":"Medium","es":"Médium","it":"Medium","ja":"おきなまじょ","ko":"점술사","pt-BR":"Médium","zh-Hans":"灵媒","zh-Hant":"靈媒"},
  "Mondaine": {"en":"Lady","de":"Dame","es":"Dama","it":"Mondana","ja":"じょせい","ko":"귀부인","pt-BR":"Dama","zh-Hans":"社交名媛","zh-Hant":"社交名媛"},
  "Montagnard": {"en":"Hiker","de":"Bergwanderer","es":"Montañero","it":"Escursionista","ja":"やまおとこ","ko":"등산가","pt-BR":"Montanhês","zh-Hans":"登山者","zh-Hant":"登山者"},
  "Montagnarde": {"en":"Hiker","de":"Bergwanderin","es":"Montañera","it":"Escursionista","ja":"やまおとこ","ko":"등산가","pt-BR":"Montanhesa","zh-Hans":"女登山者","zh-Hant":"女登山者"},
  "Montagnrad": {"en":"Hiker","de":"Bergwanderer","es":"Montañero","it":"Escursionista","ja":"やまおとこ","ko":"등산가","pt-BR":"Montanhês","zh-Hans":"登山者","zh-Hant":"登山者"},
  "Motard": {"en":"Biker","de":"Motorradfahrer","es":"Motorista","it":"Motociclista","ja":"バイカー","ko":"바이커","pt-BR":"Motociclista","zh-Hans":"摩托车手","zh-Hant":"摩托車手"},
  "Musicien": {"en":"Musician","de":"Musiker","es":"Músico","it":"Musicista","ja":"ミュージシャン","ko":"뮤지션","pt-BR":"Músico","zh-Hans":"音乐家","zh-Hant":"音樂家"},
  "Musicienne": {"en":"Musician","de":"Musikerin","es":"Música","it":"Musicista","ja":"ミュージシャン","ko":"뮤지션","pt-BR":"Musicista","zh-Hans":"女音乐家","zh-Hant":"女音樂家"},
  "Musienne": {"en":"Musician","de":"Musikerin","es":"Música","it":"Musicista","ja":"ミュージシャン","ko":"뮤지션","pt-BR":"Musicista","zh-Hans":"女音乐家","zh-Hant":"女音樂家"},
  "Mystimaniac": {"en":"Mystic","de":"Mystiker","es":"Místico","it":"Mistico","ja":"ミスティック","ko":"신비주의자","pt-BR":"Místico","zh-Hans":"神秘者","zh-Hant":"神秘者"},
  "Mécano": {"en":"Mechanic","de":"Mechaniker","es":"Mecánico","it":"Meccanico","ja":"メカニック","ko":"정비사","pt-BR":"Mecânico","zh-Hans":"机械师","zh-Hant":"機械師"},
  "Médecins": {"en":"Doctors","de":"Ärzte","es":"Médicos","it":"Medici","ja":"いしゃ","ko":"의사들","pt-BR":"Médicos","zh-Hans":"医生们","zh-Hant":"醫生們"},
  "Médium": {"en":"Psychic","de":"Psychiker","es":"Psíquico","it":"Veggente","ja":"おかっぱ","ko":"점술가","pt-BR":"Psíquico","zh-Hans":"通灵者","zh-Hant":"通靈者"},
  "Nageur": {"en":"Swimmer","de":"Schwimmer","es":"Nadador","it":"Nuotatore","ja":"スイマー","ko":"수영 선수","pt-BR":"Nadador","zh-Hans":"游泳选手","zh-Hant":"游泳選手"},
  "Nageurs": {"en":"Swimmers","de":"Schwimmer","es":"Nadadores","it":"Nuotatori","ja":"スイマーたち","ko":"수영 선수들","pt-BR":"Nadadores","zh-Hans":"游泳选手们","zh-Hant":"游泳選手們"},
  "Nageuse": {"en":"Swimmer","de":"Schwimmerin","es":"Nadadora","it":"Nuotatrice","ja":"スイマー","ko":"여수영 선수","pt-BR":"Nadadora","zh-Hans":"女游泳选手","zh-Hant":"女游泳選手"},
  "Nettoyeur": {"en":"Janitor","de":"Reiniger","es":"Limpiador","it":"Addetto alle Pulizie","ja":"そうじにん","ko":"청소부","pt-BR":"Limpador","zh-Hans":"清洁工","zh-Hant":"清潔工"},
  "Ninja Amateur": {"en":"Ninja Boy","de":"Ninjaknabe","es":"Ninja Amateur","it":"Ninja Amatore","ja":"にんじゃほっしん","ko":"아마추어 닌자","pt-BR":"Ninja Amador","zh-Hans":"业余忍者","zh-Hant":"業餘忍者"},
  "Ninja Fan": {"en":"Ninja Fan","de":"Ninja-Fan","es":"Fan de los Ninjas","it":"Fan dei Ninja","ja":"にんじゃファン","ko":"닌자 팬","pt-BR":"Fã de Ninja","zh-Hans":"忍者迷","zh-Hant":"忍者迷"},
  "Ornithologue": {"en":"Bird Keeper","de":"Vogelkenner","es":"Avicultor","it":"Ornitologo","ja":"バードキーパー","ko":"조류학자","pt-BR":"Observador de Pássaros","zh-Hans":"鸟类学家","zh-Hant":"鳥類學家"},
  "Ouvrier": {"en":"Worker","de":"Arbeiter","es":"Obrero","it":"Operaio","ja":"こうじにん","ko":"노동자","pt-BR":"Trabalhador","zh-Hans":"工人","zh-Hant":"工人"},
  "Ouvrière": {"en":"Worker","de":"Arbeiterin","es":"Obrera","it":"Operaia","ja":"こうじにん","ko":"여성 노동자","pt-BR":"Trabalhadora","zh-Hans":"女工人","zh-Hant":"女工人"},
  "PKM Ranger": {"en":"Pokémon Ranger","de":"Pokémon-Ranger","es":"Ranger Pokémon","it":"Ranger Pokémon","ja":"ポケモンレンジャー","ko":"포켓몬 레인저","pt-BR":"Ranger Pokémon","zh-Hans":"宝可梦巡护员","zh-Hant":"寶可夢巡護員"},
  "PKMN Ranger": {"en":"Pokémon Ranger","de":"Pokémon-Ranger","es":"Ranger Pokémon","it":"Ranger Pokémon","ja":"ポケモンレンジャー","ko":"포켓몬 레인저","pt-BR":"Ranger Pokémon","zh-Hans":"宝可梦巡护员","zh-Hant":"寶可夢巡護員"},
  "Patron": {"en":"Boss","de":"Chef","es":"Jefe","it":"Capo","ja":"ボス","ko":"사장","pt-BR":"Chefe","zh-Hans":"老板","zh-Hant":"老闆"},
  "Peintre": {"en":"Painter","de":"Maler","es":"Pintor","it":"Pittore","ja":"ペインター","ko":"화가","pt-BR":"Pintor","zh-Hans":"画家","zh-Hant":"畫家"},
  "Petit": {"en":"Little Boy","de":"Kleiner Junge","es":"Niño","it":"Bambino","ja":"ちいさなおとこのこ","ko":"꼬마","pt-BR":"Menino","zh-Hans":"小男孩","zh-Hant":"小男孩"},
  "Petit Sportif": {"en":"Young Athlete","de":"Junger Sportler","es":"Joven Deportista","it":"Giovane Sportivo","ja":"こどもスポーツせんしゅ","ko":"어린 운동선수","pt-BR":"Jovem Atleta","zh-Hans":"小运动员","zh-Hant":"小運動員"},
  "Petite": {"en":"Little Girl","de":"Kleines Mädchen","es":"Niña","it":"Bambina","ja":"ちいさなおんなのこ","ko":"꼬마 소녀","pt-BR":"Menininha","zh-Hans":"小女孩","zh-Hant":"小女孩"},
  "Petite & Petit": {"en":"Kids","de":"Kinder","es":"Niños","it":"Bambini","ja":"こどもたち","ko":"꼬마들","pt-BR":"Crianças","zh-Hans":"小孩们","zh-Hant":"小孩們"},
  "Petites": {"en":"Little Girls","de":"Kleine Mädchen","es":"Niñas","it":"Bambine","ja":"ちいさなおんなのこたち","ko":"꼬마 소녀들","pt-BR":"Meninhas","zh-Hans":"小女孩们","zh-Hant":"小女孩們"},
  "Pillard": {"en":"Raider","de":"Plünderer","es":"Saqueador","it":"Predatore","ja":"レイダー","ko":"약탈자","pt-BR":"Saqueador","zh-Hans":"掠夺者","zh-Hant":"掠奪者"},
  "Pilote": {"en":"Pilot","de":"Pilot","es":"Piloto","it":"Pilota","ja":"パイロット","ko":"파일럿","pt-BR":"Piloto","zh-Hans":"飞行员","zh-Hant":"飛行員"},
  "Pique-Nique": {"en":"Picnicker","de":"Picknickmacher","es":"Excursionista","it":"Gitante","ja":"ピクニックパーティー","ko":"소풍꾼","pt-BR":"Piqueniqueiro","zh-Hans":"野餐者","zh-Hant":"野餐者"},
  "Pique-nique": {"en":"Picnicker","de":"Picknickmacher","es":"Excursionista","it":"Gitante","ja":"ピクニックパーティー","ko":"소풍꾼","pt-BR":"Piqueniqueiro","zh-Hans":"野餐者","zh-Hant":"野餐者"},
  "Pkmn Ranger": {"en":"Pokémon Ranger","de":"Pokémon-Ranger","es":"Ranger Pokémon","it":"Ranger Pokémon","ja":"ポケモンレンジャー","ko":"포켓몬 레인저","pt-BR":"Ranger Pokémon","zh-Hans":"宝可梦巡护员","zh-Hant":"寶可夢巡護員"},
  "Plongeur": {"en":"Diver","de":"Taucher","es":"Buceador","it":"Sub","ja":"ダイバー","ko":"다이버","pt-BR":"Mergulhador","zh-Hans":"潜水员","zh-Hant":"潛水員"},
  "Poké Enfant": {"en":"Pokékid","de":"Pokékind","es":"PokéNiño","it":"PokéBambino","ja":"ポケこども","ko":"포케 어린이","pt-BR":"PokéCriança","zh-Hans":"宝可梦小孩","zh-Hant":"寶可夢小孩"},
  "Pokéfan": {"en":"Pokéfan","de":"Pokéfan","es":"Pokéfan","it":"Pokéfan","ja":"ポケファン","ko":"포케팬","pt-BR":"Pokéfan","zh-Hans":"宝可梦迷","zh-Hant":"寶可夢迷"},
  "Pokémaniac": {"en":"Pokémaniac","de":"Pokémaniac","es":"Pokémaniac","it":"Pokémaniac","ja":"ポケマニア","ko":"포케마니아","pt-BR":"Pokémaniac","zh-Hans":"宝可梦狂热者","zh-Hant":"寶可夢狂熱者"},
  "Pokémon Ranger": {"en":"Pokémon Ranger","de":"Pokémon-Ranger","es":"Ranger Pokémon","it":"Ranger Pokémon","ja":"ポケモンレンジャー","ko":"포켓몬 레인저","pt-BR":"Ranger Pokémon","zh-Hans":"宝可梦巡护员","zh-Hant":"寶可夢巡護員"},
  "Policier": {"en":"Police Officer","de":"Polizist","es":"Policía","it":"Poliziotto","ja":"おまわりさん","ko":"경찰관","pt-BR":"Policial","zh-Hans":"警察","zh-Hant":"警察"},
  "Pompier": {"en":"Firefighter","de":"Feuerwehrmann","es":"Bombero","it":"Pompiere","ja":"しょうぼうし","ko":"소방관","pt-BR":"Bombeiro","zh-Hans":"消防员","zh-Hant":"消防員"},
  "Pompom Girls": {"en":"Cheerleader","de":"Cheerleaderin","es":"Animadora","it":"Cheerleader","ja":"チアリーダー","ko":"치어리더","pt-BR":"Líder de Torcida","zh-Hans":"啦啦队","zh-Hant":"啦啦隊"},
  "Prof": {"en":"Psychic","de":"Psychiker","es":"Psíquico","it":"Sensitivo","ja":"エスパー","ko":"염력사","pt-BR":"Psíquico","zh-Hans":"超能力者","zh-Hant":"超能力者"},
  "Programme": {"en":"Program","de":"Programm","es":"Programa","it":"Programma","ja":"プログラム","ko":"프로그램","pt-BR":"Programa","zh-Hans":"程序","zh-Hant":"程序"},
  "Propriétaire": {"en":"Owner","de":"Inhaber","es":"Propietario","it":"Proprietario","ja":"オーナー","ko":"주인","pt-BR":"Proprietário","zh-Hans":"所有者","zh-Hant":"所有者"},
  "Présidente d'Æther": {"en":"Aether President","de":"Äther-Präsidentin","es":"Presidenta de Æther","it":"Presidente di Æther","ja":"エーテルのだいひょう","ko":"에테르 재단 회장","pt-BR":"Presidente da Æther","zh-Hans":"以太财团会长","zh-Hant":"以太財團會長"},
  "Pêcheur": {"en":"Fisherman","de":"Fischer","es":"Pescador","it":"Pescatore","ja":"つりびと","ko":"낚시꾼","pt-BR":"Pescador","zh-Hans":"钓鱼者","zh-Hant":"釣魚者"},
  "Pêcheuse": {"en":"Fisherman","de":"Fischerin","es":"Pescadora","it":"Pescatrice","ja":"つりびと","ko":"낚시꾼","pt-BR":"Pescadora","zh-Hans":"女钓鱼者","zh-Hant":"女釣魚者"},
  "Pêcheuse de Perles": {"en":"Pearl Diver","de":"Perlentaucherin","es":"Buscadora de Perlas","it":"Cercatrice di Perle","ja":"しんじゅとりむすめ","ko":"진주 채취 아가씨","pt-BR":"Pescadora de Pérolas","zh-Hans":"采珠女","zh-Hant":"採珠女"},
  "Randoneuse": {"en":"Hiker","de":"Wanderin","es":"Senderista","it":"Escursionista","ja":"ハイカー","ko":"하이커","pt-BR":"Caminhante","zh-Hans":"女徒步者","zh-Hant":"女徒步者"},
  "Randonneur": {"en":"Hiker","de":"Wanderer","es":"Senderista","it":"Escursionista","ja":"ハイカー","ko":"하이커","pt-BR":"Caminhante","zh-Hans":"徒步者","zh-Hant":"徒步者"},
  "Randonneuse": {"en":"Hiker","de":"Wanderin","es":"Senderista","it":"Escursionista","ja":"ハイカー","ko":"하이커","pt-BR":"Caminhante","zh-Hans":"女徒步者","zh-Hant":"女徒步者"},
  "Reporter": {"en":"Reporter","de":"Reporter","es":"Reportero","it":"Reporter","ja":"レポーター","ko":"리포터","pt-BR":"Repórter","zh-Hans":"记者","zh-Hant":"記者"},
  "Richard": {"en":"Rich Boy","de":"Reiches Kind","es":"Niño Rico","it":"Ricco","ja":"おぼっちゃま","ko":"부잣집 도련님","pt-BR":"Menino Rico","zh-Hans":"富家少爷","zh-Hant":"富家少爺"},
  "Rival": {"en":"Rival","de":"Rivale","es":"Rival","it":"Rivale","ja":"ライバル","ko":"라이벌","pt-BR":"Rival","zh-Hans":"竞争对手","zh-Hant":"競爭對手"},
  "Roller Skateur": {"en":"Roller Skater","de":"Rollschuhläufer","es":"Patinador en Línea","it":"Pattinatore","ja":"ローラースケーター","ko":"롤러 스케이터","pt-BR":"Patinador","zh-Hans":"轮滑者","zh-Hant":"輪滑者"},
  "Roller Skateuse": {"en":"Roller Skater","de":"Rollschuhläuferin","es":"Patinadora en Línea","it":"Pattinatrice","ja":"ローラースケーター","ko":"롤러 스케이터","pt-BR":"Patinadora","zh-Hans":"女轮滑者","zh-Hant":"女輪滑者"},
  "Ruinemaniac": {"en":"Ruin Maniac","de":"Ruinenfreak","es":"Maníaco de las Ruinas","it":"Maniaco delle Rovine","ja":"いせきマニア","ko":"유적 마니아","pt-BR":"Maníaco por Ruínas","zh-Hans":"废墟迷","zh-Hant":"廢墟迷"},
  "Ruinophile": {"en":"Ruin Maniac","de":"Ruinenfreak","es":"Maníaco de las Ruinas","it":"Maniaco delle Rovine","ja":"いせきマニア","ko":"유적 마니아","pt-BR":"Maníaco por Ruínas","zh-Hans":"废墟迷","zh-Hant":"廢墟迷"},
  "Sage": {"en":"Sage","de":"Weiser","es":"Sabio","it":"Saggio","ja":"めいそうのおとこ","ko":"현자","pt-BR":"Sábio","zh-Hans":"智者","zh-Hant":"智者"},
  "Saltimbanque": {"en":"Acrobat","de":"Akrobat","es":"Saltimbanqui","it":"Saltimbanco","ja":"アクロバット","ko":"곡예사","pt-BR":"Saltimbanco","zh-Hans":"杂耍艺人","zh-Hant":"雜耍藝人"},
  "Sbire": {"en":"Grunt","de":"Scherge","es":"Secuaz","it":"Tirapiedi","ja":"したっぱ","ko":"부하","pt-BR":"Capanga","zh-Hans":"小喽啰","zh-Hant":"小嘍囉"},
  "Sbire Team Aqua": {"en":"Team Aqua Grunt","de":"Team Aqua-Scherge","es":"Secuaz del Team Aqua","it":"Tirapiedi del Team Acqua","ja":"アクアだんしたっぱ","ko":"아쿠아단 부하","pt-BR":"Capanga do Team Aqua","zh-Hans":"海洋队小喽啰","zh-Hant":"海洋隊小嘍囉"},
  "Sbire Team Magma": {"en":"Team Magma Grunt","de":"Team Magma-Scherge","es":"Secuaz del Team Magma","it":"Tirapiedi del Team Magma","ja":"マグマだんしたっぱ","ko":"마그마단 부하","pt-BR":"Capanga do Team Magma","zh-Hans":"熔岩队小喽啰","zh-Hant":"熔岩隊小嘍囉"},
  "Sbire Team Skull": {"en":"Team Skull Grunt","de":"Team Skull-Scherge","es":"Secuaz del Team Skull","it":"Tirapiedi del Team Skull","ja":"スカルだんしたっぱ","ko":"스컬단 부하","pt-BR":"Capanga do Team Skull","zh-Hans":"骷髅队小喽啰","zh-Hant":"骷髏隊小嘍囉"},
  "Sbire Team Star": {"en":"Team Star Grunt","de":"Team Star-Scherge","es":"Secuaz del Team Star","it":"Tirapiedi del Team Star","ja":"スターだんしたっぱ","ko":"스타단 부하","pt-BR":"Capanga do Team Star","zh-Hans":"星队小喽啰","zh-Hant":"星隊小嘍囉"},
  "Sbire Team Yell": {"en":"Team Yell Grunt","de":"Team Yell-Scherge","es":"Secuaz del Team Yell","it":"Tirapiedi del Team Yell","ja":"エールだんしたっぱ","ko":"응원단 부하","pt-BR":"Capanga do Team Yell","zh-Hans":"喝彩队小喽啰","zh-Hant":"喝彩隊小嘍囉"},
  "Sbire de la": {"en":"Grunt","de":"Scherge","es":"Secuaz","it":"Tirapiedi","ja":"したっぱ","ko":"부하","pt-BR":"Capanga","zh-Hans":"小喽啰","zh-Hant":"小嘍囉"},
  "Sbire de la Team": {"en":"Grunt","de":"Scherge","es":"Secuaz","it":"Tirapiedi","ja":"したっぱ","ko":"부하","pt-BR":"Capanga","zh-Hans":"小喽啰","zh-Hant":"小嘍囉"},
  "Sbire de la Team Aqua &": {"en":"Team Aqua Grunt","de":"Team Aqua-Scherge","es":"Secuaz del Team Aqua","it":"Tirapiedi del Team Acqua","ja":"アクアだんしたっぱ","ko":"아쿠아단 부하","pt-BR":"Capanga do Team Aqua","zh-Hans":"海洋队小喽啰","zh-Hant":"海洋隊小嘍囉"},
  "Sbire de la Team Magma &": {"en":"Team Magma Grunt","de":"Team Magma-Scherge","es":"Secuaz del Team Magma","it":"Tirapiedi del Team Magma","ja":"マグマだんしたっぱ","ko":"마그마단 부하","pt-BR":"Capanga do Team Magma","zh-Hans":"熔岩队小喽啰","zh-Hant":"熔岩隊小嘍囉"},
  "Sbires de la": {"en":"Grunts","de":"Schergen","es":"Secuaces","it":"Tirapiedi","ja":"したっぱたち","ko":"부하들","pt-BR":"Capangas","zh-Hans":"小喽啰们","zh-Hant":"小嘍囉們"},
  "Scientifique": {"en":"Scientist","de":"Wissenschaftler","es":"Científico","it":"Scienziato","ja":"はかせ","ko":"과학자","pt-BR":"Cientista","zh-Hans":"科学家","zh-Hant":"科學家"},
  "Scientifique Team Flare": {"en":"Team Flare Scientist","de":"Team Flare-Wissenschaftler","es":"Científico del Team Flare","it":"Scienziato del Team Flare","ja":"フレアだんはかせ","ko":"플레어단 과학자","pt-BR":"Cientista do Team Flare","zh-Hans":"闪焰队科学家","zh-Hant":"閃焰隊科學家"},
  "Scout": {"en":"Scout","de":"Pfadfinder","es":"Explorador","it":"Scout","ja":"スカウト","ko":"스카우트","pt-BR":"Escoteiro","zh-Hans":"童子军","zh-Hant":"童子軍"},
  "Senior et Junior": {"en":"Sr. and Jr.","de":"Senior und Junior","es":"Sénior y Júnior","it":"Senior e Junior","ja":"シニアとジュニア","ko":"시니어와 주니어","pt-BR":"Sênior e Júnior","zh-Hans":"前辈与后辈","zh-Hant":"前輩與後輩"},
  "Serveur": {"en":"Waiter","de":"Kellner","es":"Camarero","it":"Cameriere","ja":"ウエイター","ko":"웨이터","pt-BR":"Garçom","zh-Hans":"服务员","zh-Hant":"服務員"},
  "Serveuse": {"en":"Waitress","de":"Kellnerin","es":"Camarera","it":"Cameriera","ja":"ウエイトレス","ko":"웨이트리스","pt-BR":"Garçonete","zh-Hans":"女服务员","zh-Hant":"女服務員"},
  "Skieur": {"en":"Skier","de":"Skifahrer","es":"Esquiador","it":"Sciatore","ja":"スキーヤー","ko":"스키어","pt-BR":"Esquiador","zh-Hans":"滑雪者","zh-Hant":"滑雪者"},
  "Skieuse": {"en":"Skier","de":"Skifahrerin","es":"Esquiadora","it":"Sciatrice","ja":"スキーヤー","ko":"스키어","pt-BR":"Esquiadora","zh-Hans":"女滑雪者","zh-Hant":"女滑雪者"},
  "Soeur Kimono": {"en":"Kimono Girl","de":"Kimono-Schwester","es":"Hermana Kimono","it":"Sorella Kimono","ja":"キモノのおんなのこ","ko":"기모노 소녀","pt-BR":"Irmã Kimono","zh-Hans":"和服姐妹","zh-Hant":"和服姐妹"},
  "Soeur Parasol": {"en":"Parasol Lady","de":"Schirmdame","es":"Sombrillera","it":"Donzella col Parasole","ja":"ひがさのおじょうさん","ko":"파라솔 아가씨","pt-BR":"Dama com Sombrinha","zh-Hans":"阳伞小姐","zh-Hant":"陽傘小姐"},
  "Soeurs Étranges": {"en":"Strange Sisters","de":"Merkwürdige Schwestern","es":"Hermanas Raras","it":"Sorelle Strane","ja":"ふしぎなしまい","ko":"이상한 자매들","pt-BR":"Irmãs Estranhas","zh-Hans":"奇怪的姐妹","zh-Hant":"奇怪的姐妹"},
  "Sportifs": {"en":"Athletes","de":"Sportler","es":"Deportistas","it":"Sportivi","ja":"スポーツせんしゅ","ko":"운동선수들","pt-BR":"Atletas","zh-Hans":"运动员们","zh-Hant":"運動員們"},
  "Sportifs en Herbe": {"en":"Young Athletes","de":"Junge Sportler","es":"Jóvenes Deportistas","it":"Giovani Sportivi","ja":"わかてスポーツせんしゅ","ko":"풋내기 운동선수들","pt-BR":"Jovens Atletas","zh-Hans":"新手运动员","zh-Hant":"新手運動員"},
  "Sr et Jr": {"en":"Sr. and Jr.","de":"Senior und Junior","es":"Sénior y Júnior","it":"Senior e Junior","ja":"シニアとジュニア","ko":"시니어와 주니어","pt-BR":"Sênior e Jr.","zh-Hans":"前辈与后辈","zh-Hant":"前輩與後輩"},
  "Sr. et Jr.": {"en":"Sr. and Jr.","de":"Senior und Junior","es":"Sénior y Júnior","it":"Senior e Junior","ja":"シニアとジュニア","ko":"시니어와 주니어","pt-BR":"Sênior e Jr.","zh-Hans":"前辈与后辈","zh-Hant":"前輩與後輩"},
  "Star": {"en":"Star","de":"Star","es":"Estrella","it":"Stella","ja":"スター","ko":"스타","pt-BR":"Estrela","zh-Hans":"明星","zh-Hant":"明星"},
  "Stratège": {"en":"Strategist","de":"Stratege","es":"Estratega","it":"Stratega","ja":"ストラテジスト","ko":"전략가","pt-BR":"Estrategista","zh-Hans":"战略家","zh-Hant":"戰略家"},
  "Supporters": {"en":"Supporters","de":"Anhänger","es":"Aficionados","it":"Supporter","ja":"サポーター","ko":"서포터즈","pt-BR":"Torcedores","zh-Hans":"支持者们","zh-Hant":"支持者們"},
  "Surfer": {"en":"Surfer","de":"Surfer","es":"Surfero","it":"Surfista","ja":"サーファー","ko":"서퍼","pt-BR":"Surfista","zh-Hans":"冲浪者","zh-Hant":"衝浪者"},
  "Surfeur": {"en":"Surfer","de":"Surfer","es":"Surfero","it":"Surfista","ja":"サーファー","ko":"서퍼","pt-BR":"Surfista","zh-Hans":"冲浪者","zh-Hant":"衝浪者"},
  "Sœur Parasol": {"en":"Parasol Lady","de":"Schirmdame","es":"Sombrillera","it":"Donzella col Parasole","ja":"ひがさのおじょうさん","ko":"파라솔 아가씨","pt-BR":"Dama com Sombrinha","zh-Hans":"阳伞小姐","zh-Hant":"陽傘小姐"},
  "Team Aqua": {"en":"Team Aqua","de":"Team Aqua","es":"Team Aqua","it":"Team Acqua","ja":"アクアだん","ko":"아쿠아단","pt-BR":"Team Aqua","zh-Hans":"海洋队","zh-Hant":"海洋隊"},
  "Team Flare": {"en":"Team Flare","de":"Team Flare","es":"Team Flare","it":"Team Flare","ja":"フレアだん","ko":"플레어단","pt-BR":"Team Flare","zh-Hans":"闪焰队","zh-Hant":"閃焰隊"},
  "Team Galaxie": {"en":"Team Galactic","de":"Team Galaxis","es":"Team Galaxia","it":"Team Galassia","ja":"ギンガだん","ko":"갤럭시단","pt-BR":"Team Galáctico","zh-Hans":"银河队","zh-Hant":"銀河隊"},
  "Team Magma": {"en":"Team Magma","de":"Team Magma","es":"Team Magma","it":"Team Magma","ja":"マグマだん","ko":"마그마단","pt-BR":"Team Magma","zh-Hans":"熔岩队","zh-Hant":"熔岩隊"},
  "Team Plasma": {"en":"Team Plasma","de":"Team Plasma","es":"Team Plasma","it":"Team Plasma","ja":"プラズマだん","ko":"플라즈마단","pt-BR":"Team Plasma","zh-Hans":"等离子队","zh-Hant":"等離子隊"},
  "Team Rainbow Rocket": {"en":"Team Rainbow Rocket","de":"Team Regenbogen-Rocket","es":"Team Arco Iris Rocket","it":"Team Razzo Arcobaleno","ja":"レインボーロケットだん","ko":"레인보우 로켓단","pt-BR":"Team Rocket Arco-Íris","zh-Hans":"彩虹火箭队","zh-Hant":"彩虹火箭隊"},
  "Team Skull": {"en":"Team Skull","de":"Team Skull","es":"Team Skull","it":"Team Skull","ja":"スカルだん","ko":"스컬단","pt-BR":"Team Skull","zh-Hans":"骷髅队","zh-Hant":"骷髏隊"},
  "Team Star": {"en":"Team Star","de":"Team Star","es":"Team Star","it":"Team Star","ja":"スターだん","ko":"스타단","pt-BR":"Team Star","zh-Hans":"星队","zh-Hant":"星隊"},
  "Tenniswoman": {"en":"Tennis Player","de":"Tennisspielerin","es":"Tenista","it":"Tennista","ja":"テニスせんしゅ","ko":"테니스 선수","pt-BR":"Tenista","zh-Hans":"女网球运动员","zh-Hant":"女網球運動員"},
  "Terreur": {"en":"Villain","de":"Bösewicht","es":"Villano","it":"Cattivone","ja":"わるもの","ko":"악당","pt-BR":"Vilão","zh-Hans":"恶棍","zh-Hant":"惡棍"},
  "Top Model": {"en":"Top Model","de":"Topmodel","es":"Top Model","it":"Top Model","ja":"トップモデル","ko":"탑 모델","pt-BR":"Top Model","zh-Hans":"超模","zh-Hant":"超模"},
  "Topdreseur": {"en":"Ace Trainer","de":"Ace-Trainer","es":"Entrenador Maestro","it":"Asso Allenatore","ja":"エースをねらえ","ko":"에이스 트레이너","pt-BR":"Ás Treinador","zh-Hans":"王牌训练师","zh-Hant":"王牌訓練師"},
  "Topdresseur": {"en":"Ace Trainer","de":"Ace-Trainer","es":"Entrenador Maestro","it":"Asso Allenatore","ja":"エースをねらえ","ko":"에이스 트레이너","pt-BR":"Ás Treinador","zh-Hans":"王牌训练师","zh-Hant":"王牌訓練師"},
  "Topdresseurs": {"en":"Ace Trainers","de":"Ace-Trainer","es":"Entrenadores Maestros","it":"Assi Allenatori","ja":"エースたち","ko":"에이스 트레이너들","pt-BR":"Ases Treinadores","zh-Hans":"王牌训练师们","zh-Hant":"王牌訓練師們"},
  "Topdresseuse": {"en":"Ace Trainer","de":"Ace-Trainerin","es":"Entrenadora Maestra","it":"Asso Allenatrice","ja":"エースをねらえ","ko":"에이스 트레이너","pt-BR":"Ás Treinadora","zh-Hans":"女王牌训练师","zh-Hant":"女王牌訓練師"},
  "Topduo": {"en":"Ace Duo","de":"Ace-Duo","es":"Dúo Maestro","it":"Asso Duo","ja":"エースデュオ","ko":"에이스 듀오","pt-BR":"Dupla Ás","zh-Hans":"王牌二人组","zh-Hant":"王牌二人組"},
  "Touriste": {"en":"Tourist","de":"Tourist","es":"Turista","it":"Turista","ja":"ツーリスト","ko":"관광객","pt-BR":"Turista","zh-Hans":"游客","zh-Hant":"遊客"},
  "Touristes": {"en":"Tourists","de":"Touristen","es":"Turistas","it":"Turisti","ja":"ツーリストたち","ko":"관광객들","pt-BR":"Turistas","zh-Hans":"游客们","zh-Hant":"遊客們"},
  "Triathlète": {"en":"Triathlete","de":"Triathlet","es":"Triatleta","it":"Triatleta","ja":"トライアスリート","ko":"트라이애슬론 선수","pt-BR":"Triatleta","zh-Hans":"铁人三项运动员","zh-Hant":"鐵人三項運動員"},
  "Ultra-Commando": {"en":"Ultra Recon Squad","de":"Ultraspürer","es":"Comando Ultra","it":"Comando Ultra","ja":"ウルトラちょうさたい","ko":"울트라 조사대","pt-BR":"Esquadrão Ultra","zh-Hans":"究极调查队","zh-Hant":"究極調查隊"},
  "Vacancier": {"en":"Vacationer","de":"Urlauber","es":"Veraneante","it":"Vacanziere","ja":"バケーション","ko":"휴가객","pt-BR":"Turista","zh-Hans":"度假者","zh-Hant":"度假者"},
  "Vacancière": {"en":"Vacationer","de":"Urlauberin","es":"Veraneante","it":"Vacanziera","ja":"バケーション","ko":"여성 휴가객","pt-BR":"Turista","zh-Hans":"女度假者","zh-Hant":"女度假者"},
  "Vacancières": {"en":"Vacationers","de":"Urlauberinnen","es":"Veraneantes","it":"Vacanziere","ja":"バケーション","ko":"여성 휴가객들","pt-BR":"Turistas","zh-Hans":"女度假者们","zh-Hant":"女度假者們"},
  "Vaurien": {"en":"Delinquent","de":"Taugenichts","es":"Gamberro","it":"Furfante","ja":"はみだしもの","ko":"불량 청소년","pt-BR":"Vagabundo","zh-Hans":"流氓","zh-Hant":"流氓"},
  "Vaurienne": {"en":"Delinquent","de":"Taugenichts","es":"Gamberra","it":"Furfanta","ja":"はみだしもの","ko":"여성 불량 청소년","pt-BR":"Vagabunda","zh-Hans":"女流氓","zh-Hant":"女流氓"},
  "Vauriens": {"en":"Delinquents","de":"Taugenichtse","es":"Gamberros","it":"Furfanti","ja":"はみだしものたち","ko":"불량 청소년들","pt-BR":"Vagabundos","zh-Hans":"流氓们","zh-Hant":"流氓們"},
  "Vieux Couple": {"en":"Old Couple","de":"Altes Paar","es":"Vieja Pareja","it":"Vecchia Coppia","ja":"ろうふうふ","ko":"노부부","pt-BR":"Casal Idoso","zh-Hans":"老夫妇","zh-Hant":"老夫婦"},
  "Vénérable": {"en":"Elder","de":"Ehrwürdiger","es":"Venerable","it":"Venerabile","ja":"ちょうろう","ko":"어른","pt-BR":"Venerável","zh-Hans":"长老","zh-Hant":"長老"},
  "Vénérables": {"en":"Elders","de":"Ehrwürdige","es":"Venerables","it":"Venerabili","ja":"ちょうろうたち","ko":"어른들","pt-BR":"Veneráveis","zh-Hans":"长老们","zh-Hant":"長老們"},
  "Écolier": {"en":"Schoolboy","de":"Schuljunge","es":"Colegial","it":"Scolaretto","ja":"しょうがくせい","ko":"초등학생","pt-BR":"Colegial","zh-Hans":"男生","zh-Hant":"男生"},
  "Écolière": {"en":"Schoolgirl","de":"Schulmädchen","es":"Colegiala","it":"Scolaretta","ja":"しょうがくせい","ko":"초등학생","pt-BR":"Colegial","zh-Hans":"女生","zh-Hant":"女生"},
  "Éleveur": {"en":"Pokémon Breeder","de":"Pokémon-Züchter","es":"Criador de Pokémon","it":"Allevatore Pokémon","ja":"そだてや","ko":"포켓몬 브리더","pt-BR":"Criador de Pokémon","zh-Hans":"宝可梦培育师","zh-Hant":"寶可夢培育師"},
  "Éleveuse": {"en":"Pokémon Breeder","de":"Pokémon-Züchterin","es":"Criadora de Pokémon","it":"Allevatrice Pokémon","ja":"そだてや","ko":"포켓몬 브리더","pt-BR":"Criadora de Pokémon","zh-Hans":"女宝可梦培育师","zh-Hant":"女寶可夢培育師"},
  "Élève": {"en":"Student","de":"Schüler","es":"Alumno","it":"Alunno","ja":"せいと","ko":"학생","pt-BR":"Aluno","zh-Hans":"学生","zh-Hant":"學生"},
  "Étudiant": {"en":"Student","de":"Student","es":"Estudiante","it":"Studente","ja":"がくせい","ko":"대학생","pt-BR":"Estudante","zh-Hans":"大学生","zh-Hant":"大學生"},
  "Étudiante": {"en":"Student","de":"Studentin","es":"Estudiante","it":"Studentessa","ja":"がくせい","ko":"여대학생","pt-BR":"Estudante","zh-Hans":"女大学生","zh-Hant":"女大學生"},
}

# Write output
with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(MAPPING, f, ensure_ascii=False, indent=2)

langs = ["de","en","es","it","ja","ko","pt-BR","zh-Hans","zh-Hant"]
print(f"✅ {len(MAPPING)} classes écrites → {OUT}")
for lang in langs:
    covered = sum(1 for v in MAPPING.values() if lang in v)
    print(f"  {lang:10}: {covered}/{len(MAPPING)}")
